// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyShNZTRRTkr1Q5OftuKh6Y76y_SruGq0',
    appId: '1:603562369302:web:b591dbeb63b890b1a27037',
    messagingSenderId: '603562369302',
    projectId: 'team-talk-flutter-app',
    authDomain: 'team-talk-flutter-app.firebaseapp.com',
    storageBucket: 'team-talk-flutter-app.firebasestorage.app',
    measurementId: 'G-XH4XQZDE9H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBnv1-Kh0gj7FSBqhhWNIUHDooNusMt-E',
    appId: '1:603562369302:android:19c41cb9626038f3a27037',
    messagingSenderId: '603562369302',
    projectId: 'team-talk-flutter-app',
    storageBucket: 'team-talk-flutter-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAczBnVKKTOwfKuIokQYzV4d-To3GMQgz0',
    appId: '1:603562369302:ios:a724aed93cfb16efa27037',
    messagingSenderId: '603562369302',
    projectId: 'team-talk-flutter-app',
    storageBucket: 'team-talk-flutter-app.firebasestorage.app',
    iosBundleId: 'com.example.teamTalkFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAczBnVKKTOwfKuIokQYzV4d-To3GMQgz0',
    appId: '1:603562369302:ios:a724aed93cfb16efa27037',
    messagingSenderId: '603562369302',
    projectId: 'team-talk-flutter-app',
    storageBucket: 'team-talk-flutter-app.firebasestorage.app',
    iosBundleId: 'com.example.teamTalkFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyShNZTRRTkr1Q5OftuKh6Y76y_SruGq0',
    appId: '1:603562369302:web:1909e137ee097a91a27037',
    messagingSenderId: '603562369302',
    projectId: 'team-talk-flutter-app',
    authDomain: 'team-talk-flutter-app.firebaseapp.com',
    storageBucket: 'team-talk-flutter-app.firebasestorage.app',
    measurementId: 'G-0VHX1411JZ',
  );
}
